name: Airflow DAG CI/CD Pipeline

on:
  push:
    branches:
      - main # Trigger workflow on push to main branch
  pull_request:
    branches:
      - main # Trigger workflow on pull requests to main branch

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies with constraints
        run: |
          pip install -r requirements.txt -c https://raw.githubusercontent.com/apache/airflow/constraints-2.3.0/constraints-3.8.txt
      
      - name: Lint the DAG
        run: pylint dags/*.py

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy DAG to Composer
        run: |
          gsutil cp dags/*.py gs://us-central1-alpha-vantage-a-5c441ef9-bucket/dags
    